import { safeWrap } from "../../../lib/safe-tool.js";

import { getCompanies as _getCompanies } from "./get-companies.js";
import { getCompanyOverview as _getCompanyOverview } from "./get-company-overview.js";
import { getActionItems as _getActionItems } from "./get-action-items.js";
import { getInsights as _getInsights } from "./get-insights.js";
import { getOpenSignals as _getOpenSignals } from "./get-open-signals.js";
import { searchTranscriptsKeyword as _searchTranscriptsKeyword } from "./search-transcripts-keyword.js";
import { searchThreadMessages as _searchThreadMessages } from "./search-thread-messages.js";
import { searchTicketMessages as _searchTicketMessages } from "./search-ticket-messages.js";
import { getContacts as _getContacts } from "./get-contacts.js";
import { getInteractionTimeline as _getInteractionTimeline } from "./get-interaction-timeline.js";
import { getBillingOverview as _getBillingOverview } from "./get-billing-overview.js";
import { getTickets as _getTickets } from "./get-tickets.js";
import { getPortfolioHealthTrend as _getPortfolioHealthTrend } from "./get-portfolio-health-trend.js";
import { searchTranscriptsSemantic as _searchTranscriptsSemantic } from "./search-transcripts-semantic.js";
import { getTeamMembers as _getTeamMembers } from "./get-team-members.js";
import { getMetrics as _getMetrics } from "./get-metrics.js";
import { getSignalDetails as _getSignalDetails } from "./get-signal-details.js";
import { briefMe as _briefMe } from "./brief-me.js";
import { myDayToday as _myDayToday } from "./my-day-today.js";
import { weeklyDigest as _weeklyDigest } from "./weekly-digest.js";
import { getTeamPortfolio as _getTeamPortfolio } from "./get-team-portfolio.js";

export const getCompanies = safeWrap(_getCompanies);
export const getCompanyOverview = safeWrap(_getCompanyOverview);
export const getActionItems = safeWrap(_getActionItems);
export const getInsights = safeWrap(_getInsights);
export const getOpenSignals = safeWrap(_getOpenSignals);
export const searchTranscriptsKeyword = safeWrap(_searchTranscriptsKeyword);
export const searchThreadMessages = safeWrap(_searchThreadMessages);
export const searchTicketMessages = safeWrap(_searchTicketMessages);
export const getContacts = safeWrap(_getContacts);
export const getInteractionTimeline = safeWrap(_getInteractionTimeline);
export const getBillingOverview = safeWrap(_getBillingOverview);
export const getTickets = safeWrap(_getTickets);
export const getPortfolioHealthTrend = safeWrap(_getPortfolioHealthTrend);
export const searchTranscriptsSemantic = safeWrap(_searchTranscriptsSemantic);
export const getTeamMembers = safeWrap(_getTeamMembers);
export const getMetrics = safeWrap(_getMetrics);
export const getSignalDetails = safeWrap(_getSignalDetails);
export const briefMe = safeWrap(_briefMe);
export const myDayToday = safeWrap(_myDayToday);
export const weeklyDigest = safeWrap(_weeklyDigest);
export const getTeamPortfolio = safeWrap(_getTeamPortfolio);
